### ISSUE TITLE
X-AnyLabeling-EdgeSAM demo support

### ISSUE THREAD

**Issue by CVHub520** [chongzhou96/EdgeSAM#14]
Hi, @chongzhou96, thanks a lot for your outstanding work! 

I've successfully integrated EdgeSAM into [X-AnyLabeling](https://github.com/CVHub520/X-AnyLabeling), and your open-source contribution has been invaluable for achieving efficient execution on devices with limited computational resources.

**Comment by chongzhou96** [comment]
Thanks a lot! I've updated the readme accordingly.
