### ISSUE TITLE
Finetuning

### ISSUE THREAD

**Issue by a333klm** [chongzhou96/EdgeSAM#20]
I'd like to finetune EdgeSAM for a specific task.
Is there code already available?
Have you experience in finetuning EdgeSAM?

**Comment by chongzhou96** [comment]
I haven't tried finetuning EdgeSAM on any other datasets. But we plan to do so for SA-1B. You might first refer to our training code as a start point. Check out [this readme file](https://github.com/chongzhou96/EdgeSAM/blob/master/README_TRAIN.md) for details.
