### ISSUE TITLE
whole image

### ISSUE THREAD

**Issue by LooperzZ** [chongzhou96/EdgeSAM#22]
Hello, how can I predict the whole picture without using a mouse click to determine the segmentation coordinate point?

**Comment by Greywan** [comment]
https://github.com/chongzhou96/EdgeSAM/issues/5

**Comment by Greywan** [comment]
> Hello, how can I predict the whole picture without using a mouse click to determine the segmentation coordinate point?
you can see this:
https://github.com/chongzhou96/EdgeSAM/issues/5
