### ISSUE TITLE
model edge_sam not found

### ISSUE THREAD

**Issue by pascal-maker** [chongzhou96/EdgeSAM#28]
when running import sys
sys.path.append("..")
from segment_anything import sam_model_registry, SamPredictor

sam_checkpoint = "/content/EfficientSAM/edge_sam.pth"
model_type = "edge_sam"

device = "cuda"

sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
sam.to(device=device)

predictor = SamPredictor(sam)  ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/tmp/ipykernel_11959/398106226.py](https://localhost:8080/#) in <cell line: 10>()
      8 device = "cuda"
      9 
---> 10 sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
     11 sam.to(device=device)
     12 

KeyError: 'edge_sam'

**Comment by chongzhou96** [comment]
Please try `from edge_sam import SamPredictor, sam_model_registry` instead of `from segment_anything import sam_model_registry, SamPredictor`.
