### ISSUE TITLE
Request for NCNN Integration in EdgeSAM Project

### ISSUE THREAD

**Issue by umitkacar** [chongzhou96/EdgeSAM#3]
Hello EdgeSAM Team,

I hope this message finds you well. I am reaching out to request the integration of NCNN into the EdgeSAM project. NCNN, known for its high performance in neural network inference on mobile devices, seems like a perfect fit for EdgeSAM's objectives in edge computing scenarios.

The inclusion of NCNN would provide several benefits, including:

1. **Enhanced Performance**: Leveraging NCNN's optimized routines could improve the efficiency and speed of EdgeSAM's computations, especially on devices with limited resources.

2. **Broader Compatibility**: With NCNN's support for multiple platforms, EdgeSAM could extend its usability across a wider range of mobile and embedded devices.

3. **Community Engagement**: Integrating popular and widely-used frameworks like NCNN can attract more contributors and users to the EdgeSAM project, fostering a larger community and encouraging collaborative development.

I believe that the synergy between EdgeSAM and NCNN could lead to significant advancements in edge computing applications. I am looking forward to your thoughts on this suggestion and hope to see a collaboration that benefits both projects and their respective communities.

Thank you for considering my request.

Best regards,
Umit

**Comment by chongzhou96** [comment]
Hi Umit,

Thank you for the suggestion. Are you referring to the [this repo](https://github.com/Tencent/ncnn)? If so, I need to get familiar with it first. In the meantime, any PR is welcome.
