### ISSUE TITLE
The result is incorrect after training according to README_TRAIN.md

### ISSUE THREAD

**Issue by isyanan1024** [chongzhou96/EdgeSAM#40]
"(Phase 2) Is the Prompt-in-the-Loop Knowledge Distillation training finished after completion, or are there other steps? Why is the trained model ckpt_epoch_4.pth 110M, but the model provided by the author, edge_sam_3x.pth, only 38M? Also, when loading the model, a warning appears: _IncompatibleKeys(missing_keys=['image_encoder.features.0.0.c.weight', 'image_encoder.features.0.0.bn.weight', 'image_encoder.features.0.0.bn.bias', 'image_encoder.features.0.0.bn.running_mean', 'image_encoder.features.0.0.bn.running_var', 'image_encoder.features.0.2.c.weight', 'image_encoder.features.0.2.bn.weight', 'image_encoder.features.0.2.bn.bias', 'image_encoder.features.0.2.bn.running_mean', 'image_encoder.features.0.2.bn.running_var', 'image_encoder.features.1.token_mixer.0.conv.c.weight', 'image_encoder.features.1.token_mixer.0.conv.bn.weight', 'image_encoder.features.1.token_mixer.0.conv.bn.bias', 'image_encoder.features.1.token_mixer.0.conv.bn.running_mean', 'image_encoder.features.1.token_mixer.0.conv.bn.running_var', 'image_encoder.features.1.token_mixer.0.conv1.c.weight', 'image_encoder.features.1.token_mixer.0.conv1.bn.weight', 'image_encoder.features.1.token_mixer.0.conv1.bn.bias', 'image_encoder.features.1.token_mixer.0.conv1.bn.running_mean', ] Did I miss any steps?"

**Comment by gold123fish** [comment]
Excuse me, have you solved it? I also have a big tip
missing_keys=['image_encoder.features.0.0.c.weight', 'image_encoder.features.0.0.bn.weight', 'image_encoder.features.0.0.bn.bias',........

Is this the weight/repvit_m1_distill_300.th you are using for your weights? I couldn't find the same one, I only found weightsvepvit_ma0_9_istill_300e.pth

**Comment by ooe1123** [comment]
```
import torch
with open("./output/rep_vit_m1_fuse_enc_dec_4m_ft_bp_iter2b_sa_distill/default/ckpt_epoch_4.pth", "rb") as f:
	state_dict = torch.load(f)

torch.save(state_dict["model"], "weights/trained_model.pth")
```
