### ISSUE TITLE
Grounded-Edge-SAM demo support

### ISSUE THREAD

**Issue by rentainhe** [chongzhou96/EdgeSAM#7]
Hello! Thanks a lot for your great work! We've already supported [grounded-edga-sam demo](https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/EfficientSAM/grounded_edge_sam.py) in [Grounded-Segment-Anything](https://github.com/IDEA-Research/Grounded-Segment-Anything) !

**Comment by chongzhou96** [comment]
Thank you! I've updated the README accordingly.
