### ISSUE TITLE
tensorrt&rknn&altas inference

### ISSUE THREAD

**Issue by SoulProficiency** [chongzhou96/EdgeSAM#8]
感谢edgeSam提供了边缘端及移动端的sam方案，目前想使用tensorrt&rknn&altas进行部署和推理，请问有相应的参考资料么？

**Comment by chongzhou96** [comment]
Sorry, I’m not familiar with the frameworks that you mentioned.

**Comment by SoulProficiency** [comment]
thanks a lot
